context: dev
configs:
  dev:
    base_url: https://ibstest.allinpay.com/yst/yst-service-api
    private_key_str: MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQgiaZmB+feACtziE8SYjVZsaQwLNLRiyO8ebSupeoWIF2gCgYIKoEcz1UBgi2hRANCAATwEo0zq6KaB992PToWeJH52LmfS0sFovnB8/LMaoIAOTlFJtA3YgjWXKlO3KT+GqOCfCC4xE60isCr28tqy7hM
    allinpay_public_key_str: MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEu9LNkJlyLtjJxtQWIGlcZ/hyHt5eZ7LEH1nfOiK1H9HsE1cMPu5KK5jZVTtAyc7lPMXixUMirf6A3tMbuMbgqg==
    app_id: 21762000921804636162
    secret_key: 878427523d3525e070298d44481b8d2e
    phone:
  beta:
    base_url:
    private_key_str:
    allinpay_public_key_str:
    app_id:
    secret_key:
    phone:
